In [1]:
import os
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
model, nfeat, maf, censoring, cv, date = 'epi', 'f100', 'maf0.4', '0.1', '0', '2024-04-07'
if model == 'add':
    model_long = 'additive'
elif model == 'epi':
    model_long = '2way_epistasis'
elif model == 'het':
    model_long = 'heterogeneous'
elif model == 'me':
    model_long = 'main_effect'

In [3]:
objects = []
with (open('pipeline/pickled_cv_models/'+model+'/'+model+'_'+nfeat+'_'+maf+'/cens_'+censoring+'/ExSTraCS_'+cv+'_'+date, "rb")) as file:
    while True:
        try:
            objects.append(pickle.load(file))
        except EOFError:
            break

In [4]:
trainedModel = objects[0]

In [5]:
#load data
data = pd.read_csv('pipeline/cv_sim_data/cv_'+model+'/'+model+'_'+nfeat+'_'+maf+\
    '/'+model_long+'_cens'+censoring+'_surv_'+date+'_CV_'+cv+'_Train.txt', sep = '\t', header = 0)
timeLabel = 'eventTime'
censorLabel = 'eventStatus'
inst = 'inst'

dataHeaders = data.drop([timeLabel,censorLabel, inst],axis=1).columns.values
headers = dataHeaders

In [6]:
trainedModel.export_final_rule_population(headers,censorLabel,filename="output/popData.csv")
populationData = pd.read_csv("output/popData.csv")
display(populationData.head())

,Specified Values,Specified Attribute Names,eventStatus,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Deletion Probability,Correct Count,Match Count,Epoch Complete
0,0,N65,"0,36.5625",1.000000,0.870538,11,311.069503,49983,6704,0.01,0.010734,32291,41391,True
1,"0, 0","M0P5, M0P6","71.19772643100195,87.1675",0.971221,0.737048,5,358.546354,49998,9201,0.02,0.005410,2182,4470,True
2,1,M0P5,"0,63.1175",1.000000,0.799786,4,281.869574,49983,13347,0.01,0.003463,17695,18155,True
3,0,N65,"0,50.1875",1.000000,0.800820,8,311.069503,49983,15092,0.01,0.007807,28541,33518,True
4,0,N54,"0,36.5625",1.000000,0.869886,2,301.020938,49983,19191,0.01,0.001876,23638,30384,True

In [8]:
populationData = populationData.sort_values('Accuracy', ascending=False)
populationData = populationData
display(populationData)

,Specified Values,Specified Attribute Names,eventStatus,Fitness,Accuracy,Numerosity,Avg Match Set Size,TimeStamp GA,Iteration Initialized,Specificity,Deletion Probability,Correct Count,Match Count,Epoch Complete
684,"2, 2, 0","N17, N64, N97","47.3275,62.6725",1.000000,1.000000,1,348.327980,49505,49505,0.03,0.001051,1,1,True
342,"2, 2, 0, 0","N17, N64, N67, N97","47.3275,62.6725",1.000000,1.000000,1,348.327980,49505,45505,0.04,0.001051,6,6,True
666,"1, 2, 0, 2, 1","N9, N10, N84, M0P5, M0P6","81.90180536330581,86.47639189065158",1.000000,0.999932,1,367.040593,49310,49310,0.05,0.001108,1,2,True
507,"1, 0, 2, 0, 0, 0","N3, N19, N68, N70, N95, M0P6","82.85047247875899,109.10946613932475",1.000000,0.999447,1,327.566735,49700,47697,0.06,0.000989,10,11,True
405,"1, 0, 0, 2, 0, 0, 0","N3, N19, N61, N68, N70, N95, M0P6","82.85047247875899,109.10946613932475",1.000000,0.999447,1,327.136680,49700,46500,0.07,0.000987,15,16,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,1,N25,"0,78.85",0.781839,0.008618,2,307.373486,49981,42738,0.01,0.001924,3531,3814,True
348,"0, 0","N5, N61","0,78.85",0.781839,0.008570,2,315.254886,49983,45638,0.02,0.001903,3847,4227,True
413,0,N61,"0,78.85",0.781839,0.008544,1,312.400243,49983,46591,0.01,0.000943,3471,3827,True
230,0,N16,"0,78.85",0.781838,0.008447,1,322.280431,49983,43380,0.01,0.000973,6152,6777,True
495,"0, 0","N45, N62","0,78.85",0.781838,0.008431,1,290.189549,49971,47538,0.02,0.000876,2147,2392,True

In [10]:
populationData.head(10).to_csv('output/Table8.csv')

In [ ]:
os.remove("output/popData.csv")